### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by jps-github** [jps-github/furima-35456#9]
# URL
https://furima-35456.herokuapp.com/

# Basic認証
ID: admin
パスワード: 1234

# 登録済みユーザー

[出品者]
メールアドレス: seller@test.com
パスワード: seller123

[購入者]
メールアドレス: buyer@test.com
パスワード: buyer123

**Comment by takahirohoriguchi** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

**Comment by jps-github** [comment]
🎉✨🎉✨🎉✨ありがとうございました！✨🎉✨🎉✨🎉
